version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  cluster:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  producer:
    build:
      context: ./producer
    container_name: producer
    networks:
      - kafka-network
    ports:
      - "5000:8081"
    depends_on:
      - cluster

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    networks:
      - kafka-network
    ports:
      - "8082:8082"
    depends_on:
      - cluster

networks:
  kafka-network: # Define a custom network
    driver: bridge